services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &
        sleep 10
        ollama pull qwen2.5:0.5b
        wait
    networks:
      - chat_network

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
    env_file:
      - .env
    networks:
      - chat_network

  backend:
    build: ./
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - ollama
      - database
    networks:
      - chat_network

volumes:
  ollama_data: {}
  pgdata: {}

networks:
  chat_network:
    driver: bridge
